config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root "articles#index"
  get 'search', to: 'articles#search'
  get 'filter', to: 'articles#filter'
  resources :articles do 
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy
    has_one_attached :header_image
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }



end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern 

    VALID_STATUSES = ['public', 'private', 'archived']

    included do 
        validates :status, inclusion: { in: VALID_STATUSES }
    end
    
    class_methods do 
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def search 
    @articles = Article.where("title LIKE ?", "%" + params[:q] + "%")
  end

  def filter
    @articles = Article.where("category LIKE ?", "%" +  params[:filter] + "%")
  end

  def show 
    @article = Article.find(params[:id])
  end

  def new 
    @article = Article.new
  end

  def create 
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit 
    @article = Article.find(params[:id])
  end

  def update 
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to edit_article_path(@article)
    else 
      render :edit
    end
  end

  def destroy 
    @article = Article.find(params[:id])
    @article.destroy 

    redirect_to root_path
  end

  private 
    def article_params 
      params.require(:article).permit(:title, :body, :status, :category, :page, :header_image)
    end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    http_basic_authenticate_with name: "ivan", password: "123", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    

    private 
    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def boostrap_class(alert)
        { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
          danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
      end
    
      def flash_messages(_opts = {})
        flash.each do |msg_type, message|
          concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
            concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
              concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
            end)
            concat message
          end)
        end
        nil
      end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
  <div class="form-group col">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col">
    <%= form.label :body %><br>
    <%= form.text_area :body, class: "form-control" %><br>
  </div>
  </div>

    <div class="input-group mb-3">
      <%= form.file_field :header_image, class: "form-control" %>
      <div class="mt-1">
        <% if article.header_image.present? %>
        <%= image_tag(article.header_image, width: '100%') %>
      <% end %>
    </div>
    </div>
   
  <div class="form-group col">
    <%= form.label :status %><br>
    <%= form.select(:status, ['public', 'private', 'archived'], {}, {:class => 'custom-select'}) %>
  </div>
  <div class="form-group col">
    <%= form.label :category %><br>
    <%= form.select(:category, ['Sunset', 'Nature', 'Other'], {}, {:class => 'custom-select'}) %>
  </div>
  <div class="actions d-flex justify-content-center">
        <%= form.submit 'Create', class: "btn btn-success" %>
        <%= link_to "Back", articles_path, class: "btn btn-default ml-3" %> 
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<div class="d-flex justify-content-center">
    <%= link_to 'Preview', @article, class: "btn btn-warning mt-2" %>
</div>

app/views/articles/filter.html.erb
<h1 class="text-center">Search Results</h1>
<%= flash_messages %>
<div class="d-flex flex-wrap align-items-center justify-content-center mt-5">
  <% @articles.each do |article| %>
    <%= link_to article_path(article), class: 'text-decoration-none' do %>
    <div class="card text-center m-3 post-card" style="width: 35%">
        <% if article.header_image.present? %>
        <div class="header-img card-img-top" style="background-image: url(<%= url_for(article.header_image) %>);"></div>
        <% end %>

      <div class="card-body">
        <h5 class="card-title mb-1 text-dark"><%= article.title %></h5>
         <p class="card-text mb-1 text-decoration-none"><%= article.body.truncate(50) %></p>
          </div>
          <div class="card-body">
            <%= link_to 'Show', article_path(article), class: "btn btn-info" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </div>
    <% end %>

<% end %>
</div>

app/views/articles/index.html.erb
<%= flash_messages %>
<div class="d-flex flex-wrap align-items-center justify-content-center mt-5">
  <% if @articles.length==0 %> 
    <h1>No posts. Create one, don't be shy 😁</h1>
  <% else %>
    <% @articles.each do |article| %>
      <%= link_to article_path(article), class: 'text-decoration-none' do %>
      <div class="card text-center m-3 post-card" style="width: 35%">
          <% if article.header_image.present? %>
          <div class="header-img card-img-top" style="background-image: url(<%= url_for(article.header_image) %>);"></div>
          <% end %>
        <div class="card-body">
          <h5 class="card-title mb-1 text-dark"><%= article.title %></h5>
          <p class="card-text mb-1 text-decoration-none"><%= article.body.truncate(50) %></p>
            </div>
            <div class="card-body">
              <%= link_to 'Show', article_path(article), class: "btn btn-info" %>
              <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </div>
      <% end %>
    <% end %>

<% end %>
</div>
<div class="d-flex justify-content-center">
  <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
  This blog currently has <%= Article.public_count %> public articles!
</div>

app/views/articles/new.html.erb
<h1 class="text-center">New article 🗒</h1>
<div class="d-flex justify-content-center">
    <%= render "form", article: @article %>
</div>

app/views/articles/search.html.erb
  <h1 class="text-center">Search results</h1>
<%= flash_messages %>
<div class="d-flex flex-wrap align-items-center justify-content-center mt-5">
  <% @articles.each do |article| %>
    <%= link_to article_path(article), class: 'text-decoration-none' do %>
    <div class="card text-center m-3 post-card" style="width: 35%">
        <% if article.header_image.present? %>
        <div class="header-img card-img-top" style="background-image: url(<%= url_for(article.header_image) %>);"></div>
        <% end %>

      <div class="card-body">
        <h5 class="card-title mb-1 text-dark"><%= article.title %></h5>
         <p class="card-text mb-1 text-decoration-none"><%= article.body.truncate(50) %></p>
          </div>
          <div class="card-body">
            <%= link_to 'Show', article_path(article), class: "btn btn-info" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </div>
    <% end %>

<% end %>
</div>

app/views/articles/show.html.erb
<%= flash_messages %>
<div class="row custom">
    <div class="col-lg-10 offset-lg-1">
        <div class="card post-card-read mb-5">
            <% if @article.header_image.present? %>
                <div class="header-image" style="background-image: url(<%= url_for(@article.header_image) %>);"></div>
            <% end %>
            <div class="card-body">
                <div class="pl-5 pr-5 pt-4 pb-4">
                    <h1 class="card-title mb-5"><%= @article.title %></h1>
                    <p class="card-text mb-4"><%= @article.body %></p>
                </div>
                
            </div>
            <div class="card-body text-center">
                <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary" %>
                <%= link_to "Back", articles_path, class: "btn btn-warning" %>
            </div>
        </div>
    </div>
</div>

<div class="comment-section">
    <div class="comments-main">
    <h2>Comments</h2>
    <% if @article.comments.length==0 %>
        <h4>No comments yet. Be the first who reacted to this! 🤩</h4>
    <% else %>
        <%= render @article.comments %>
    <% end %>
    <div>
<h4>Add a comment:</h4>
<%= render 'comments/form' %>
</div>
</div>
</div>

</div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :heading %>
    <%= form.text_field :heading %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :display %>
    <%= form.check_box :display %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.heading %></td>
        <td><%= category.body %></td>
        <td><%= category.display %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @category.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @category.body %>
</p>

<p>
  <strong>Display:</strong>
  <%= @category.display %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<div class="custom-card-profile card border-primary mb-3">
    <div class="card-header">By: <%= comment.commenter %></div>
    <div class="card-body">
      <p class="card-text"><%= comment.body %></p>
      <p>
        <%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    </p>
    </div>
  </div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

<div class="card d-flex justify-content-center" style="width: 25rem;">
    <div class="card-body">
        <div class="form-group">
            <%= form.label :commenter %><br>
            <%= form.text_field :commenter, class: 'form-control' %>

    </div>
        <div class="form-group">
            <%= form.label :body %><br>
            <%= form.text_area :body, class: 'form-control' %>
    </div>
            <p>
        <%= form.label :status %><br>
        <%= form.select(:status, ['public', 'private', 'archived'], {}, {:class => 'custom-select'}) %>
    </p>
    <div>
        <%= form.submit "Post", class: 'btn btn-primary' %>
    </div>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Ruby blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse" style="display: flex !important;">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item mr-3">
            <%= link_to "List", articles_path, class: 'btn btn-info' %>
          </li>
          <li class="nav-item mr-3">
            <%= link_to "New", new_article_path, class: 'btn btn-success' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item mr-3">
              <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %>
            </li>
          <% else %>
            <li class="nav-item mr-3">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item mr-3">
              <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item mr-3">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></li>
            </li>
          <% end %>
        </ul>
        <form action="/filter" class="form-inline my-2 my-lg-0" id="filter-form">
          <%= select_tag "filter", options_for_select(['Choose filter', 'Sunset', 'Nature', 'Other']), class: 'custom-select', id:'filter_select', onchange: 'clickSubmit()' %>
        </form>
        <form class="form-inline mt-2 ml-4 mt-md-0" action="/search">
          <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav> 
       

    <div id="main-container" class="container" >
      <%= yield %>
    </div>
    <script>
      function clickSubmit() { 
        $('form#filter-form').submit();
      }
    </script>
  </body>
</html>